---
title: "NY NOAA"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)

```

Scatterplot {data-width=600}
-----------------------------------------------------------------------

### Tmax versus tmin with size of precipitation

```{r, echo=FALSE, warning=FALSE, message=FALSE}

set.seed(1)

data(ny_noaa)

noaa = ny_noaa %>% 
  janitor::clean_names() %>% 
  separate(date, into = c("year", "month", "day"), sep = "-") %>% 
  mutate(
    prcp = prcp / 10,
    tmin = as.integer(tmin) / 10,
    tmax = as.integer(tmax) / 10
    ) %>% 
  sample_n(1000)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
noaa %>% 
  plot_ly(x = ~tmax, y = ~tmin,
  color = ~month, size = ~prcp
)
```



Column {data-width=400}
-----------------------------------------------------------------------

### Boxplot

```{r, echo=FALSE, warning=FALSE, message=FALSE}
noaa %>%
  group_by(year) %>% 
  plot_ly(y = ~tmax, color = ~year, type = "box",
          colors = "Set2")
```


### Line chart

```{r, echo=FALSE, warning=FALSE, message=FALSE}
noaa %>%
  filter(month == "07") %>% 
  plot_ly(x = ~year, y = ~tmax, name = 'Tmax', type = 'scatter', mode = 'lines+markers') %>%
  add_trace(y = ~tmin, name = 'Tmin', mode = 'lines+markers') %>%
  add_trace(y = ~prcp, name = 'Precipitation', mode = 'markers')
```
